### ISSUE TITLE
Music identification

### ISSUE THREAD

**Issue by perguth** [peermusic/research#3]
Possibly API-providing databases:
- [x] http://freedb.org
- [x] http://freedb2.org
- [x] http://gnudb.org
- [x] http://musicbrainz.org
- https://en.wikipedia.org/wiki/List_of_online_music_databases

See https://github.com/peermusic/user-stories/issues/11

**Comment by ryomiyaichi** [comment]
What about ACRCloud? They have a javascript api on github, but there is no documentation.
